config/routes.rb
Rails.application.routes.draw do
  get 'payment/checkout'
  post 'payment/checkout'
  resources :line_items
  resources :carts
  get 'gallery/index'
  get 'gallery/search'
  post 'gallery/search'
  post 'gallery/index'
  resources :stores
  get 'admin/index'
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'home/index'
  get 'home/contact'
  root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :store

	belongs_to :cart
  	
	def total_price
		store.price * quantity
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    @cart = current_cart
    product = Store.find(params[:store_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:cart_id, :store_id, :quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.number_field :cart_id %>
  </div>

  <div class="field">
    <%= form.label :store_id %>
    <%= form.number_field :store_id %>
  </div>
  <div class="field">
    <%= form.label :store_name %>
    <%= form.text_field :store_name %>
  </div>
  <div class="field">
    <%= form.label :store_price %>
    <%= form.number_field :store_price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
	<tr id="current_item">
<% else %>
	<tr>
<% end %>
		<td><%= line_item.quantity %> &times;</td>
		<td><%= line_item.store.name %></td>
		<td class="item_price">₹<%= (line_item.total_price) %></td>
	</tr>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>
<img src="/assets/main.png" height="450px" width="100%">
<h1 style="color:brown;text-align:center;">Shopping Cart status</h1><br>
<section class="h-100 h-custom">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="table-responsive">
                    
          <table class="table" border ="2" >
            <thead>
              <tr>
                <th scope="col" >Store Name  </th>
                <th scope="col" >price</th>
                <th scope="col"> Quantity</th>
                <th scope="col">Amount</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @line_items.each do |line_item| %>
                <tr>
                  <td><%= line_item.store.name %></td>
                  <td><%= line_item.store.price%></td>
                  <td><%= line_item.quantity %></td>
                  <td><%= line_item.total_price %></td> 
                  <td><%= link_to 'Show', line_item %></td>
                  <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
                  <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section><br>
 
<div style=" text-align:center;">    
  <%= link_to 'Go to cart', carts_path %>
</div><br><br>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<p>
  <strong>Store:</strong>
  <%= @line_item.store_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<p>
  <strong>Store Price:</strong>
  ₹<%= @line_item.store.price %>
</p>

<p>
  <strong>Store Name:</strong>
  <%= @line_item.store.name %>
</p>

<p>
  <strong>Amount:</strong>
  ₹<%= @line_item.total_price %>
</p>

<%= link_to 'Next', line_items_path %>